wiremind/remoulade

tests/test_cli.py

Something is wrong with TRAVIS and the test_cli

fix(test_cli) on travis

---

docs/source/guide.rst
dramatiq/middleware/retries.py
tests/test_actors.py
tests/test_rabbitmq.py
tests/test_redis.py

set default max_retries to 0

---

dramatiq/middleware/pipelines.py
tests/test_composition.py

fix: #8 
Should I submit a PR to dramatiq ? This is really broken

fix(pipeline): pipe_ignore from next_message

---

docs/source/changelog.rst
docs/source/global.rst
remoulade/actor.py
remoulade/broker.py
remoulade/composition.py
remoulade/message.py
remoulade/middleware/__init__.py
remoulade/middleware/middleware.py
remoulade/results/__init__.py
remoulade/results/backend.py
remoulade/results/backends/redis.py
remoulade/results/constants.py
remoulade/results/errors.py
remoulade/results/middleware.py
tests/middleware/test_prometheus.py
tests/test_broker.py
tests/test_cli.py
tests/test_composition.py
tests/test_results.py

store_error in result backend

---

docs/source/changelog.rst
docs/source/cookbook.rst
docs/source/global.rst
remoulade/__init__.py
remoulade/broker.py
remoulade/common.py
remoulade/composition.py
remoulade/composition_result.py
remoulade/errors.py
remoulade/message.py
remoulade/middleware/pipelines.py
remoulade/result.py
remoulade/results/__init__.py
remoulade/results/backend.py
remoulade/results/backends/local.py
remoulade/results/backends/redis.py
remoulade/results/backends/stub.py
remoulade/results/errors.py
tests/test_composition.py
tests/test_results.py

Result backend mandatory for this functionality.
I will separe group and pipelines in different files but after this for diff reason.
I think there is more to do afterwards with group completion etc...

Add support for pipeline of groups

---

docs/source/changelog.rst
docs/source/global.rst
remoulade/composition_result.py
remoulade/result.py
remoulade/results/backend.py
remoulade/results/backends/redis.py
tests/test_results.py

it uses redis exists which reduce the cost of retriving the
completion.

CollectionResults.completed_count do not fetch results

---

docs/source/guide.rst
remoulade/brokers/rabbitmq.py
remoulade/worker.py
tests/conftest.py
tests/test_actors.py
tests/test_rabbitmq.py
tests/test_watch.py

BREAKING CHANGE: higher priorities are now processed before to be
consistent with rabbimq.

feat(priority): add priority support in rabbitmq

---

docs/source/cookbook.rst
remoulade/__init__.py
remoulade/cancel/middleware.py
remoulade/composition.py
remoulade/results/backend.py
tests/test_cancel.py

the cancelable option is to complex and does not bring anything
fix #72

feat(cancel): delete cancelable option

---

docs/source/guide.rst
remoulade/brokers/local.py
tests/conftest.py
tests/test_local.py

this was inconsistent and led to misuses.

fix(local): local broker do not declare its middleware anymore

---

remoulade/__init__.py
remoulade/scheduler/__init__.py
remoulade/scheduler/scheduler.py
remoulade/scheduler/utils.py
setup.py
tests/test_scheduler.py

scheduler is depending on redis which is an extra_dependency: it need to
be in it's own module.

chore(module): put scheduler in its own module

---

docs/source/changelog.rst
remoulade/helpers/reduce.py

feat(reduce): Add reduce size

---

docs/source/changelog.rst
remoulade/api/__init__.py
remoulade/api/main.py
remoulade/broker.py
remoulade/common.py
remoulade/errors.py
remoulade/state/__init__.py
remoulade/state/backend.py
remoulade/state/backends/redis.py
remoulade/state/backends/stub.py
remoulade/state/middleware.py
setup.py
tests/state/test_state_api.py
tests/state/test_state_objects.py

Create API to get the state of the message in a backend. Fix #107

---

docs/source/changelog.rst
remoulade/api/main.py
remoulade/common.py
remoulade/state/backend.py
remoulade/state/backends/redis.py
remoulade/state/backends/stub.py
remoulade/state/middleware.py
setup.py
tests/conftest.py
tests/middleware/test_message_state.py
tests/state/test_backend.py
tests/state/test_state_api.py
tests/state/test_state_objects.py

- States: {Enqueue, End, Started}
- Add priority to the messages

Storage time of state  change.

---

remoulade/middleware/prometheus.py
setup.cfg
tox.ini

Upgrade isort to avoid lint problem, 
guide
https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/

fix: upgrade cli flags isort.

---

remoulade/results/backends/redis.py

chore: remove unused method _get.

---

benchmarks/bench.py
docs/source/changelog.rst
remoulade/api/main.py
remoulade/api/schema.py
remoulade/state/backend.py
remoulade/state/middleware.py
tests/middleware/test_message_state.py
tests/state/test_state_api.py
tests/state/test_state_objects.py

feat: add api method to  get remoulade groups

---

remoulade/api/main.py

chore(api): remove args and kwargs from serialization for getting all messages

---

remoulade/api/main.py
remoulade/state/backend.py
remoulade/state/middleware.py
tests/state/test_state_api.py
tests/state/test_state_objects.py

feat(api): add url to requeue a message.

---

README.md

1. fix example in the readme
2. fix URL logo in the readme
3. fix URL user guide
4. add section to dashboard

chore: minor fix and update readme.

---

docs/source/changelog.rst
remoulade/middleware/__init__.py
remoulade/middleware/max_memory.py
remoulade/middleware/middleware.py
remoulade/worker.py
tests/middleware/test_max_memory.py

which stop a worker if its memory exceed max_memory

feat(middleware): add MaxMemory

---

docs/source/_static/custom.css
docs/source/changelog.rst
docs/source/conf.py
docs/source/getting_started.rst
docs/source/index.rst
docs/source/reference.rst
setup.py

Getting started

---

CONTRIBUTORS.md
docs/source/changelog.rst
remoulade/actor.py
remoulade/middleware/current_message.py

Issue 317:
- typing fixed for get_current_message
Issue 315:
- typing added for actor.py method send, send_with_options, message and message_with_options

feat(typing): fix issues 315 and 317

---

docs/source/changelog.rst
remoulade/state/backends/postgres.py
tests/conftest.py

Add future flag to True to help cayzn to upgrade sqlalchemy to 2.0

feat: add future flag to True

---

docs/source/changelog.rst
remoulade/brokers/rabbitmq.py
remoulade/middleware/retries.py
tests/test_rabbitmq.py

Add support for declaring queue as quorum type
Add support for escalating queues on retry

feat(quorum): quorum type and escalate queue on retry support

---

.gitignore
.pre-commit-config.yaml
docs/source/changelog.rst
remoulade/__init__.py
remoulade/__main__.py
remoulade/brokers/rabbitmq.py
remoulade/cancel/backends/redis.py
remoulade/helpers/redis_client.py
remoulade/middleware/time_limit.py
remoulade/rate_limits/backends/redis.py
remoulade/results/backends/redis.py
remoulade/state/backends/redis.py
setup.py
tests/middleware/test_time_limit.py

- add a socket timeout for all redis connection
- more agressive approach in case TimeLimit middleware is fired

feat: Timeout
